name: haptic_feedback_pro
description: "A Flutter plugin for triggering rich haptic feedback on iOS and Android. Supports impact, notification, selection, and full vibration types."
version: 1.0.2
homepage: https://nutriscan.app
repository: https://github.com/NesanSelvan/haptic_feedback_pro
issue_tracker: https://github.com/NesanSelvan/haptic_feedback_pro/issues

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.haptic_feedback_pro
        pluginClass: HapticFeedbackProPlugin
      ios:
        pluginClass: HapticFeedbackProPlugin
